### ISSUE TITLE
authorization / user 'groups'

### ISSUE THREAD

**Issue by dcalacci** [HumanDynamics/rhythm-server#24]
clients should only get events for meetings that they're a part of.

right now, every client receives every event (including computed turn events, that run every 5s for every client).

I suggest that we follow the following steps for doing authorization (at least for the first deployment / with getsmarter): 
1. user clicks button 
2. we send a payload from the GS system that includes an API access token / secret
3. when the client socket connects, they send over the participant ID, the meeting ID, and the auth token / secret
4. we add filters for all events that only send them out to sockets/connections that match the appropriate meeting ID (as in the [feathers docs](http://docs.feathersjs.com/real-time/filtering.html))

does this make sense?

**Comment by ryannealmes** [comment]
Looks exactly what we need.
